environment: prod

deployment:
  image:
    tag: 6
  replicas: 1
  labels:
    full-name: crossplane-app-frontend-prod

configmap: 
  nginxConf: |-
    location /api {
        # Now that we use Istio, we need to specify the http version to 1.1 for it to work (https://www.reddit.com/r/devops/comments/k0ooaw/envoy_426_http_issue/)
        proxy_http_version 1.1;
        
        proxy_pass http://crossplane-app-backend-prod-deployment:3000/;
    }
