system: my-app

service: backend

port: 3000

deployment:
  image:
    repository: tferrari92/my-app-backend # This value was modified by the initial-setup script
    tag: crossplane-minikube-lab
  replicas: 1
    
  labels:
    system: my-app
    service: backend

database:
  # includeDatabase: true
  cloudProvider: aws
  dbProvider: postgresql
  version: 13
  size: small
  # databases:
  #   - my-app-backend-db-1
    # ESTO NO FUNCIONA
    # - my-app-backend-db-2
    # - my-app-backend-db-3



    

# environment: dev

# deployment:
#   image:  
#     tag: crossplane-minikube-lab
#   replicas: 1

#   labels:
#     environment: dev
#     app: my-app-backend-dev