apiVersion: devopstoolkitseries.com/v1alpha1
kind: AppClaim
metadata:
  name: devops-toolkit
  labels:
    app-owner: vfarcic
spec:
  id: devops-toolkit
  compositionSelector:
    matchLabels:
      type: frontend
  parameters:
    namespace: a-team
    image: vfarcic/devops-toolkit-series:4.0.0
    host: devops-toolkit.127.0.0.1.nip.io


    # lo q dice eeste archivo es. Ey! quiero una composition basada en este appclain. Quiero la composition q tiene el label type: frontend