environment: dev

deployment:
  image:
    tag: 5
  replicas: 1
  labels:
    full-name: my-app-frontend-dev

configmap: 
  nginxConf: |-
    location /api {
        proxy_pass http://my-app-backend-dev-service:3000/; 
    }
