environment: prod

deployment:
  image:
    tag: 6
  replicas: 1
  labels:
    full-name: my-app-frontend-prod

configmap: 
  nginxConf: |-
    location /api {   
        proxy_pass http://my-app-backend-prod-service:3000/;
    }
