apiVersion: devopstoolkitseries.com/v1alpha1
kind: AppClaim
metadata:
  name: {{ .Values.system }}-{{ .Values.service }}-{{ .Values.environment }}-appclaim
  labels:
    app-owner: tferrari
spec:
  id: {{ .Values.system }}-{{ .Values.service }}-{{ .Values.environment }}
  compositionSelector:
    matchLabels:
      type: frontend
  parameters:
    namespace: {{ .Values.system }}-{{ .Values.environment }}
    image: {{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}
    port: {{ .Values.port }}
    dbSecret: {{ .Values.host }}
      name:
      namespace:
    db:
      version: 5.7


    # lo q dice eeste archivo es. Ey! quiero una composition basada en este appclain. Quiero la composition q tiene el label type: frontend