# apiVersion: v1
# kind: Secret
# metadata:
#   name: silly-demo-db-password
# data:
#   password: cG9zdGdyZXM=
# ---

apiVersion: devopstoolkitseries.com/v1alpha1
kind: AppClaim
metadata:
  name: {{ .Values.system }}-{{ .Values.service }}-{{ .Values.environment }}-appclaim
  labels:
    {{- range $key, $value := .Values.deployment.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  id: {{ .Values.system }}-{{ .Values.service }}-{{ .Values.environment }}
  compositionSelector:
    matchLabels:
      type: backend
  parameters:
    namespace: {{ .Values.system }}-{{ .Values.environment }}
    image: {{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}
    port: {{ .Values.port }}
    # host: terraform-20240723144510407800000018.ct60s04eu0uw.us-east-1.rds.amazonaws.com