# Create the secret with the database password with the following command:
# kubectl create secret generic -n my-app-dev my-app-backend-dev-database-password --from-literal=password=postgres
# Or use this manifest:

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.system }}-{{ .Values.service }}-db-password
data:
  password: cG9zdGdyZXM=
---

apiVersion: devopstoolkitseries.com/v1alpha1
kind: SQLClaim
metadata:
  name: {{ .Values.system }}-{{ .Values.service }}-sqlclaim
spec:
  id: {{ .Values.system }}-{{ .Values.service }}-db
  compositionSelector:
    matchLabels:
      provider: {{ .Values.database.cloudProvider }}
      db: {{ .Values.database.dbProvider }}
  parameters:
    version: {{ .Values.database.version  | quote }} 
    size: {{ .Values.database.size }}

    # ESTE PARAMETRO NO SE QUE FUNCION CUMPLE PORQ SE CREA UNA SOLA DB CON EL NOMBRE DEL ID
    # databases:
    #   {{- range .Values.database.databases }}
    #   - {{ . }}
    #   {{- end }}