apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.system }}-{{ .Values.service }}-{{ .Values.environment }}-db-password
data:
  password: cG9zdGdyZXM=
---
apiVersion: devopstoolkitseries.com/v1alpha1
kind: SQLClaim
metadata:
  name: {{ .Values.system }}-{{ .Values.service }}-{{ .Values.environment }}-app-claim
spec:
  id: {{ .Values.system }}-{{ .Values.service }}-{{ .Values.environment }}-db
  compositionSelector:
    matchLabels:
      provider: aws
      db: postgresql
  parameters:
    version: "13"
    size: small
    databases:
      - {{ .Values.system }}-{{ .Values.service }}-{{ .Values.environment }}-db
