apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-backend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io # Adding the finalizer enables cascading delete. If this isn't used, when you delete the application, the application will be removed from ArgoCD but the resources will remain active in the cluster.
spec:
  destination:
    namespace: my-app
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm-charts/my-app/backend
    repoURL: https://github.com/tomasferrarisenda/crossplane-minikube-lab.git # This value was modified by the initial-setup python script
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true