apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  name: aatt-demo-vpc
spec:
  forProvider:
    enableDnsHostnames: true
    enableDnsSupport: true
    cidrBlock: 10.0.0.0/16
    region: us-east-1
    tags:
      Name: aatt-demo-vpc
  providerConfigRef:
    name: aws


