apiVersion: devopstoolkitseries.com/v1alpha1
kind: AppClaim
metadata:
  name: {{ .Values.system }}-{{ .Values.service }}-{{ .Values.environment }}-appclaim
  labels:
    app-owner: vfarcic
spec:
  id: {{ .Values.system }}-{{ .Values.service }}-{{ .Values.environment }}
  compositionSelector:
    matchLabels:
      type: backend
  parameters:
    namespace: a-team
    image: vfarcic/silly-demo:1.0.8
    port: 8080
    host: silly-demo.54.159.206.46.nip.io